[package]
name = "lights"
version = "0.1.3"
authors = ["njaremko <njaremko@gmail.com>"]
description = "A command line Hue light controller"
license = "MIT"

[dependencies]
clap = "2.25.0"
reqwest = "0.7.0"
regex = "0.2"
serde = "1.0.9"
serde_derive = "1.0.9"
serde_json = "1.0.2"
